name: nectaar
description: "Nectar — online grocery shop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  dio: ^5.11.1
  easy_localization: ^3.0.8
  equatable: ^3.0.0
  flash: ^3.1.1
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  get_it: ^9.3.0
  shared_preferences: ^2.5.5

dev_dependencies:
  build_runner: ^2.15.1
  flutter_gen_runner: ^5.15.0
  flutter_gen: ^5.15.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: ibm_plex_sans_arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
    - family: aclonica
      fonts:
        - asset: assets/fonts/Aclonica-Regular.ttf
          weight: 400
